import { expect, test, type Page } from "@playwright/test";
import { readFile } from "node:fs/promises";

test.setTimeout(180_000);

async function openSketch(page:Page){await page.goto("/");await page.waitForFunction(()=>Boolean(window.__crawlerApp)&&Object.values(window.__crawlerApp.readiness()).every((status)=>status==="ready"));await page.locator("#edit-sketch").click();await page.evaluate(()=>window.__crawlerApp.chooseOriginSketchSupport("xy"));const canvas=page.getByLabel("3D viewport");const box=await canvas.boundingBox();if(!box)throw new Error("viewport has no bounds");return{canvas,box,overlay:page.getByLabel("Editable sketch geometry")};}
async function invoke(page:Page,key:string){await page.locator('[data-ribbon-flyout="draw"]').click();await page.locator(`[data-ribbon-run="${key}"]`).click();}
async function points(canvas:import("@playwright/test").Locator,box:{width:number;height:number},values:readonly[number,number][]){for(const[x,y]of values)await canvas.click({force:true,position:{x:box.width*x,y:box.height*y}});}
async function sourceLines(page:Page){const context=await openSketch(page);await invoke(page,"line");await points(context.canvas,context.box,[[.30,.70],[.30,.30],[.70,.30],[.70,.70]]);await page.keyboard.press("Escape");await page.keyboard.press("Escape");await expect(context.overlay.locator(".sketch-entity")).toHaveCount(3,{timeout:60_000});return context;}
async function clearSimpleSelection(overlay:import("@playwright/test").Locator){const selected=overlay.locator(".sketch-entity.selected");for(let guard=0;guard<4&&await selected.count();guard+=1)await selected.first().click({force:true,modifiers:["Control"]});await expect(selected).toHaveCount(0);}

test("P2 creation method panels invoke distinct rectangle circle arc polygon and slot variants",async({page})=>{
  const{canvas,box,overlay}=await openSketch(page);let count=0;
  await invoke(page,"rect");await page.locator("#sketch-creation-variant").selectOption("center");await points(canvas,box,[[.32,.40],[.39,.48]]);count+=6;await expect(overlay.locator(".sketch-entity")).toHaveCount(count,{timeout:60_000});
  await invoke(page,"circle");await page.locator("#sketch-creation-variant").selectOption("three_point");await points(canvas,box,[[.48,.34],[.53,.28],[.58,.34]]);count+=1;await expect(overlay.locator(".sketch-entity")).toHaveCount(count,{timeout:60_000});
  await invoke(page,"arc");await page.locator("#sketch-creation-variant").selectOption("three_point");await points(canvas,box,[[.62,.42],[.68,.34],[.74,.42]]);count+=1;await expect(overlay.locator(".sketch-entity")).toHaveCount(count,{timeout:60_000});
  await invoke(page,"polygon");await page.locator("#sketch-creation-variant").selectOption("circumscribed");await page.locator("#sketch-polygon-sides").fill("5");await page.locator("#sketch-polygon-sides").press("Tab");await points(canvas,box,[[.40,.68],[.46,.68]]);count+=5;await expect(overlay.locator(".sketch-entity")).toHaveCount(count,{timeout:60_000});
  await invoke(page,"slot");await page.locator("#sketch-creation-variant").selectOption("overall");await points(canvas,box,[[.58,.68],[.76,.68],[.58,.64]]);count+=4;await expect(overlay.locator(".sketch-entity")).toHaveCount(count,{timeout:60_000});
  const recipes=await page.evaluate(()=>window.__crawlerApp.sketchDraft()?.recipes);expect(Object.values(recipes??{}).some((recipe)=>recipe.kind==="polygon"&&recipe.mode==="circumscribed")).toBe(true);expect(Object.values(recipes??{}).some((recipe)=>recipe.kind==="slot"&&recipe.mode==="overall")).toBe(true);
});

test("tool-first tangent circle collects curve operands before placement",async({page})=>{const{canvas,box,overlay}=await sourceLines(page);await clearSimpleSelection(overlay);await invoke(page,"circle");await page.locator("#sketch-creation-variant").selectOption("two_tangent");await overlay.locator(".sketch-entity:not(.selected)").first().click({force:true});await overlay.locator(".sketch-entity:not(.selected)").first().click({force:true});await expect(page.locator("#active-tool-point-progress")).toContainText("2 / 2 curves");await points(canvas,box,[[.48,.48]]);await expect(overlay.locator(".sketch-entity")).toHaveCount(4,{timeout:60_000});});

test("tool-first tangent arc collects its source curve",async({page})=>{const{canvas,box,overlay}=await sourceLines(page);await clearSimpleSelection(overlay);await invoke(page,"arc");await page.locator("#sketch-creation-variant").selectOption("tangent");await overlay.locator(".sketch-entity:not(.selected)").first().click({force:true});await expect(page.locator("#active-tool-point-progress")).toContainText("1 / 1 curves");await points(canvas,box,[[.30,.50],[.46,.55]]);await expect(overlay.locator(".sketch-entity")).toHaveCount(4,{timeout:60_000});});

test("tool-first text-on-path collects its source curve",async({page})=>{const{canvas,box,overlay}=await sourceLines(page);await clearSimpleSelection(overlay);await invoke(page,"text");await page.locator("#sketch-text-value").fill("I");await page.locator("#sketch-text-on-path").check();await overlay.locator(".sketch-entity:not(.selected)").first().click({force:true});await expect(page.locator("#active-tool-point-progress")).toContainText("1 / 1 curves");await points(canvas,box,[[.38,.38]]);await expect.poll(()=>page.evaluate(()=>Object.values(window.__crawlerApp.sketchDraft()?.recipes??{}).some((recipe)=>recipe.kind==="text"&&Boolean(recipe.path)))).toBe(true);});

test("selection-first tangent circle retains preselected operands",async({page})=>{const{canvas,box,overlay}=await sourceLines(page);for(let index=0;index<2;index+=1)await overlay.locator(".sketch-entity:not(.selected)").first().click({force:true,modifiers:["Control"]});await invoke(page,"circle");await page.locator("#sketch-creation-variant").selectOption("three_tangent");await points(canvas,box,[[.50,.50]]);await expect(overlay.locator(".sketch-entity")).toHaveCount(4,{timeout:60_000});});

test("selection-first tangent arc retains its preselected operand",async({page})=>{const{canvas,box,overlay}=await sourceLines(page);await invoke(page,"arc");await page.locator("#sketch-creation-variant").selectOption("tangent");await points(canvas,box,[[.30,.50],[.46,.55]]);await expect(overlay.locator(".sketch-entity")).toHaveCount(4,{timeout:60_000});});

test("retained sketch text edits, follows a path, explodes, and SVG/DXF controls perform real interchange",async({page})=>{
  const{canvas,box,overlay}=await openSketch(page);
  await invoke(page,"arc");await points(canvas,box,[[.48,.48],[.58,.48],[.48,.38]]);await page.keyboard.press("Escape");await overlay.locator(".sketch-entity").first().click({force:true});
  await invoke(page,"text");await page.locator("#sketch-text-value").fill("A");await page.locator("#sketch-text-height").fill("4");await page.locator("#sketch-text-on-path").check();await points(canvas,box,[[.48,.58]]);
  await expect(page.locator(".sketch-text-panel").filter({hasText:"Explode"})).toBeVisible({timeout:60_000});
  const recipeId=await page.evaluate(()=>Object.entries(window.__crawlerApp.sketchDraft()?.recipes??{}).find(([,recipe])=>recipe.kind==="text")?.[0]);expect(recipeId).toBeTruthy();
  const retainedText=page.locator('[data-recipe-field="text"]');await retainedText.fill("I");await retainedText.press("Tab");await expect.poll(()=>page.evaluate(()=>Object.values(window.__crawlerApp.sketchDraft()?.recipes??{}).find((recipe)=>recipe.kind==="text")?.text)).toBe("I");
  const beforeExplode=await overlay.locator(".sketch-entity").count();await page.locator("#sketch-text-explode").click();await expect.poll(()=>page.evaluate(()=>Object.values(window.__crawlerApp.sketchDraft()?.recipes??{}).some((recipe)=>recipe.kind==="text"))).toBe(false);await expect(overlay.locator(".sketch-entity")).toHaveCount(beforeExplode);
  await page.locator(".sketch-context-palette > summary").click();
  const svgDownload=page.waitForEvent("download");await page.locator("#sketch-export-svg").click();expect((await svgDownload).suggestedFilename()).toMatch(/\.svg$/);
  const dxfDownload=page.waitForEvent("download");await page.locator("#sketch-export-dxf").click();expect((await dxfDownload).suggestedFilename()).toMatch(/\.dxf$/);
  const beforeImport=await overlay.locator(".sketch-entity").count();await page.locator("#sketch-import-input").setInputFiles({name:"native.svg",mimeType:"image/svg+xml",buffer:Buffer.from('<svg xmlns="http://www.w3.org/2000/svg"><line x1="0" y1="0" x2="12" y2="0"/><circle cx="20" cy="5" r="3"/><path d="M 0 10 C 4 16 8 4 12 10"/><path d="M 14 10 Q 18 16 22 10"/><path d="M 24 10 A 4 3 0 0 1 32 10"/></svg>')});await expect(overlay.locator(".sketch-entity")).toHaveCount(beforeImport+5,{timeout:60_000});
  const beforeDxfImport=await overlay.locator(".sketch-entity").count();const dxf=`0\nSECTION\n2\nHEADER\n9\n$ACADVER\n1\nAC1015\n9\n$INSUNITS\n70\n4\n0\nENDSEC\n0\nSECTION\n2\nENTITIES\n0\nLINE\n8\nSKETCH\n1001\nCRAWLER\n1000\nline:imported\n10\n0\n20\n20\n30\n0\n11\n12\n21\n20\n31\n0\n0\nCIRCLE\n8\nSKETCH\n1001\nCRAWLER\n1000\ncircle:imported\n10\n20\n20\n20\n30\n0\n40\n3\n0\nARC\n8\nSKETCH\n1001\nCRAWLER\n1000\narc:imported\n10\n30\n20\n20\n30\n0\n40\n5\n50\n0\n51\n90\n0\nENDSEC\n0\nEOF\n`;await page.locator("#sketch-import-input").setInputFiles({name:"native.dxf",mimeType:"application/dxf",buffer:Buffer.from(dxf)});await expect(overlay.locator(".sketch-entity")).toHaveCount(beforeDxfImport+3,{timeout:60_000});
  const standardSvgDownload=page.waitForEvent("download");await page.locator("#sketch-export-svg").click();const standardSvgPath=await(await standardSvgDownload).path();expect(standardSvgPath).toBeTruthy();const exportedSvg=await readFile(standardSvgPath!,"utf8");expect(exportedSvg).toMatch(/ d="[^"]* C /);expect(exportedSvg).toMatch(/ d="[^"]* Q /);expect(exportedSvg).toMatch(/ d="[^"]* A /);const metadataFreeSvg=exportedSvg.replace(/\sdata-crawler-native="[^"]*"/g,"");const beforeStandardRoundTrip=await overlay.locator(".sketch-entity").count();await page.locator("#sketch-import-input").setInputFiles({name:"standard-native.svg",mimeType:"image/svg+xml",buffer:Buffer.from(metadataFreeSvg)});await expect.poll(()=>overlay.locator(".sketch-entity").count(),{timeout:60_000}).toBeGreaterThan(beforeStandardRoundTrip);const kinds=await page.evaluate(()=>Object.values(window.__crawlerApp.sketchDraft()?.geometry??{}).map((entity)=>entity.geometry.kind));expect(kinds).toContain("control_point_spline");expect(kinds).toContain("conic");expect(kinds).toContain("elliptical_arc");
});
