//! Deterministic native feature execution over Crawler's pinned Monstertruck kernel.

use std::{
    collections::{BTreeMap, BTreeSet},
    f64::consts::TAU,
    num::NonZeroUsize,
};

#[cfg(not(target_arch = "wasm32"))]
use monstertruck_meshing::prelude::*;
use monstertruck_modeling::{
    Edge, Face, FilletOptions, FilletProfile, Point3, RadiusSpec, Shell, Solid, Vector3, Vertex,
    Wire, builder, fillet_edges, profile,
};
#[cfg(not(target_arch = "wasm32"))]
use monstertruck_solid::ShapeOpsError;
use serde::{Deserialize, Serialize};
use thiserror::Error;

/// Contract schema for persisted feature requests and results.
pub const FEATURE_KERNEL_SCHEMA_VERSION: u16 = 1;
const NANOMETERS_PER_MODEL_UNIT: f64 = 1_000_000.0;
const MICRODEGREES_PER_REVOLUTION: i64 = 360_000_000;
const MAX_EXACT_NANOMETERS: i64 = 9_007_199_254_740_991;
const MAX_QUALIFIED_BOOLEAN_CELLS: usize = 4_096;

/// Caller-owned request envelope. No identity is generated by the kernel.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeatureRequest {
    pub schema_version: u16,
    pub document_id: String,
    pub feature_id: String,
    pub output_body_id: String,
    pub operation: FeatureOperation,
}

/// Native M2 operations qualified by this crate.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum FeatureOperation {
    Revolve(RevolveInput),
    Boolean(BooleanInput),
    Fillet(EdgeTreatmentInput),
    Chamfer(EdgeTreatmentInput),
    Shell(ShellInput),
    Mirror(MirrorInput),
    Transform(TransformInput),
    LinearPattern(LinearPatternInput),
    CircularPattern(CircularPatternInput),
}

/// Exact rectangular radial profile revolved around a principal axis.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RevolveInput {
    pub axis_origin_nm: [i64; 3],
    pub axis: PrincipalAxis,
    pub inner_radius_nm: i64,
    pub outer_radius_nm: i64,
    pub axial_start_nm: i64,
    pub axial_end_nm: i64,
    pub sweep_microdegrees: i64,
    pub divisions: u32,
    pub tolerance_nm: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PrincipalAxis {
    X,
    Y,
    Z,
}

/// Boolean feature with caller ordering preserved exactly.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BooleanInput {
    pub operation: BooleanKind,
    pub target: BodySnapshot,
    pub tools: Vec<BodySnapshot>,
    pub tolerance_nm: i64,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BooleanKind {
    Union,
    Cut,
    Intersect,
}

/// One or more stable topology edges treated with an exact constant radius.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct EdgeTreatmentInput {
    pub target: BodySnapshot,
    pub edge_stable_ids: Vec<u64>,
    pub radius_nm: i64,
    pub divisions: u32,
    pub tolerance_nm: i64,
}

/// Hollow-shell request. Crawler qualifies exact axis-aligned prismatic bodies
/// with one removed planar face and fails closed for other topology.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ShellInput {
    pub target: BodySnapshot,
    pub removed_face_stable_ids: Vec<u64>,
    pub wall_thickness_nm: i64,
    pub tolerance_nm: i64,
}

/// Separates direct body transforms from feature-history re-evaluation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "semantics", rename_all = "snake_case")]
pub enum TransformSource {
    Body {
        body: BodySnapshot,
    },
    FeatureSequence {
        ordered_feature_ids: Vec<String>,
        resolved_body: BodySnapshot,
    },
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MirrorInput {
    pub source: TransformSource,
    pub plane_origin_nm: [i64; 3],
    pub plane_normal: PrincipalAxis,
    pub tolerance_nm: i64,
}

/// Exact translation of one durable body. Feature-sequence semantics remain
/// explicit and fail closed until feature-graph re-evaluation is available.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TransformInput {
    pub source: TransformSource,
    pub translation_nm: [i64; 3],
    pub tolerance_nm: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LinearPatternInput {
    pub source: TransformSource,
    /// Ordered caller-owned body IDs, including the untransformed instance.
    pub instance_body_ids: Vec<String>,
    pub step_nm: [i64; 3],
    pub tolerance_nm: i64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CircularPatternInput {
    pub source: TransformSource,
    /// Ordered caller-owned body IDs, including the untransformed instance.
    pub instance_body_ids: Vec<String>,
    pub axis_origin_nm: [i64; 3],
    pub axis: PrincipalAxis,
    pub step_microdegrees: i64,
    pub tolerance_nm: i64,
}

/// Save/load-ready kernel body paired with its caller identity.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct BodySnapshot {
    pub body_id: String,
    pub solid_json: Vec<u8>,
    pub evidence: GeometryEvidence,
}

/// Deterministic geometry evidence independent of topology object addresses.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct GeometryEvidence {
    pub vertex_count: usize,
    pub edge_count: usize,
    pub face_count: usize,
    pub bounds_nm: AxisAlignedBoundsNm,
    pub volume_model_units3: f64,
    pub deterministic_digest: String,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct AxisAlignedBoundsNm {
    pub min: [i64; 3],
    pub max: [i64; 3],
}

/// Successful feature result ready for document persistence.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct FeatureResult {
    pub schema_version: u16,
    pub document_id: String,
    pub feature_id: String,
    pub output: BodySnapshot,
    /// Ordered input body identities used by the operation.
    pub ordered_input_body_ids: Vec<String>,
    /// Ordered instance identities for patterns; empty for singular features.
    #[serde(default)]
    pub instance_body_ids: Vec<String>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorCategory {
    InvalidInput,
    Numerical,
    EmptyResult,
    Unsupported,
}

/// Stable feature failure with caller recovery context.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, Error)]
#[error("{message}")]
pub struct FeatureError {
    pub category: ErrorCategory,
    pub message: String,
    pub field: Option<String>,
    pub recovery: String,
    /// Original bodies are returned byte-for-byte when an operation refuses.
    #[serde(default)]
    pub preserved_inputs: Vec<BodySnapshot>,
    pub problematic_reference: Option<Box<ProblematicReference>>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProblematicReference {
    pub kind: ReferenceKind,
    pub stable_id: String,
    pub ordered_index: Option<usize>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ReferenceKind {
    Body,
    Edge,
    Face,
    Feature,
}

/// Executes one deterministic feature request against the pinned native kernel.
pub fn execute(request: &FeatureRequest) -> Result<FeatureResult, FeatureError> {
    validate_envelope(request)?;
    let (mut solid, ordered_input_body_ids, instance_body_ids, tolerance) = match &request.operation
    {
        FeatureOperation::Revolve(input) => {
            validate_revolve(input)?;
            (
                execute_revolve(input)?,
                Vec::new(),
                Vec::new(),
                input.tolerance_nm,
            )
        }
        FeatureOperation::Boolean(input) => {
            validate_boolean(input)?;
            let ids = std::iter::once(input.target.body_id.clone())
                .chain(input.tools.iter().map(|tool| tool.body_id.clone()))
                .collect();
            (execute_boolean(input)?, ids, Vec::new(), input.tolerance_nm)
        }
        FeatureOperation::Fillet(input) => {
            validate_edge_treatment(input)?;
            let id = input.target.body_id.clone();
            (
                execute_edge_treatment(input, FilletProfile::Round)?,
                vec![id],
                Vec::new(),
                input.tolerance_nm,
            )
        }
        FeatureOperation::Chamfer(input) => {
            validate_edge_treatment(input)?;
            let id = input.target.body_id.clone();
            (
                execute_edge_treatment(input, FilletProfile::Chamfer)?,
                vec![id],
                Vec::new(),
                input.tolerance_nm,
            )
        }
        FeatureOperation::Shell(input) => {
            validate_shell(input)?;
            let id = input.target.body_id.clone();
            (
                execute_shell(input)?,
                vec![id],
                Vec::new(),
                input.tolerance_nm,
            )
        }
        FeatureOperation::Mirror(input) => {
            validate_mirror(input)?;
            let body = resolve_transform_source(&input.source)?;
            (
                execute_mirror(input, body)?,
                vec![body.body_id.clone()],
                Vec::new(),
                input.tolerance_nm,
            )
        }
        FeatureOperation::Transform(input) => {
            validate_transform(input)?;
            let body = resolve_transform_source(&input.source)?;
            (
                execute_transform(input, body)?,
                vec![body.body_id.clone()],
                Vec::new(),
                input.tolerance_nm,
            )
        }
        FeatureOperation::LinearPattern(input) => {
            validate_linear_pattern(input)?;
            let body = resolve_transform_source(&input.source)?;
            (
                execute_linear_pattern(input, body)?,
                vec![body.body_id.clone()],
                input.instance_body_ids.clone(),
                input.tolerance_nm,
            )
        }
        FeatureOperation::CircularPattern(input) => {
            validate_circular_pattern(input)?;
            let body = resolve_transform_source(&input.source)?;
            (
                execute_circular_pattern(input, body)?,
                vec![body.body_id.clone()],
                input.instance_body_ids.clone(),
                input.tolerance_nm,
            )
        }
    };
    if solid.boundaries().is_empty() || solid.face_iter().next().is_none() {
        return Err(failure(
            ErrorCategory::EmptyResult,
            "operation produced no solid faces",
            None,
            "edit the feature so the result has non-zero volume",
        ));
    }
    solid.ensure_topology_stable_ids();
    let evidence = geometry_evidence(&solid, tolerance, request)?;
    let solid_json = serde_json::to_vec(&solid).map_err(|error| {
        failure(
            ErrorCategory::Unsupported,
            format!("kernel body cannot be serialized: {error}"),
            None,
            "simplify the feature geometry before saving",
        )
    })?;
    Ok(FeatureResult {
        schema_version: FEATURE_KERNEL_SCHEMA_VERSION,
        document_id: request.document_id.clone(),
        feature_id: request.feature_id.clone(),
        output: BodySnapshot {
            body_id: request.output_body_id.clone(),
            solid_json,
            evidence,
        },
        ordered_input_body_ids,
        instance_body_ids,
    })
}

fn validate_envelope(request: &FeatureRequest) -> Result<(), FeatureError> {
    if request.schema_version != FEATURE_KERNEL_SCHEMA_VERSION {
        return Err(failure(
            ErrorCategory::Unsupported,
            format!("unsupported schema version {}", request.schema_version),
            Some("schema_version"),
            "migrate the feature DTO to schema version 1",
        ));
    }
    for (field, value) in [
        ("document_id", request.document_id.as_str()),
        ("feature_id", request.feature_id.as_str()),
        ("output_body_id", request.output_body_id.as_str()),
    ] {
        if value.trim().is_empty() {
            return Err(failure(
                ErrorCategory::InvalidInput,
                format!("{field} must be a non-empty caller-supplied identity"),
                Some(field),
                "supply the stable identity stored by the document",
            ));
        }
    }
    Ok(())
}

fn validate_revolve(input: &RevolveInput) -> Result<(), FeatureError> {
    for (field, value) in [
        ("inner_radius_nm", input.inner_radius_nm),
        ("outer_radius_nm", input.outer_radius_nm),
        ("axial_start_nm", input.axial_start_nm),
        ("axial_end_nm", input.axial_end_nm),
    ] {
        exact_nm(field, value)?;
    }
    exact_positive_nm("tolerance_nm", input.tolerance_nm)?;
    for (index, value) in input.axis_origin_nm.into_iter().enumerate() {
        exact_nm(&format!("axis_origin_nm[{index}]"), value)?;
    }
    if input.inner_radius_nm < 0 {
        return Err(invalid("inner_radius_nm", "must be zero or greater"));
    }
    if input.outer_radius_nm <= input.inner_radius_nm {
        return Err(invalid(
            "outer_radius_nm",
            "must be greater than inner_radius_nm",
        ));
    }
    if input.axial_end_nm <= input.axial_start_nm {
        return Err(invalid(
            "axial_end_nm",
            "must be greater than axial_start_nm",
        ));
    }
    if !(1..=MICRODEGREES_PER_REVOLUTION).contains(&input.sweep_microdegrees) {
        return Err(invalid(
            "sweep_microdegrees",
            "must be between 1 and 360000000",
        ));
    }
    let minimum_divisions = if input.sweep_microdegrees == MICRODEGREES_PER_REVOLUTION {
        4
    } else {
        1
    };
    if input.divisions < minimum_divisions || input.divisions > 4096 {
        return Err(invalid(
            "divisions",
            "must be 4..=4096 for a closed sweep or 1..=4096 for a partial sweep",
        ));
    }
    Ok(())
}

fn validate_boolean(input: &BooleanInput) -> Result<(), FeatureError> {
    exact_positive_nm("tolerance_nm", input.tolerance_nm)?;
    validate_snapshot("target", &input.target)?;
    if input.tools.is_empty() {
        return Err(invalid(
            "tools",
            "must contain at least one ordered tool body",
        ));
    }
    for (index, tool) in input.tools.iter().enumerate() {
        validate_snapshot(&format!("tools[{index}]"), tool)?;
    }
    Ok(())
}

fn validate_edge_treatment(input: &EdgeTreatmentInput) -> Result<(), FeatureError> {
    validate_snapshot("target", &input.target)?;
    exact_positive_nm("radius_nm", input.radius_nm)?;
    exact_positive_nm("tolerance_nm", input.tolerance_nm)?;
    if input.edge_stable_ids.is_empty() {
        return Err(invalid(
            "edge_stable_ids",
            "must contain at least one stable edge reference",
        ));
    }
    if input.edge_stable_ids.contains(&0) {
        return Err(invalid(
            "edge_stable_ids",
            "cannot contain the unassigned stable ID 0",
        ));
    }
    if !(1..=256).contains(&input.divisions) {
        return Err(invalid("divisions", "must be between 1 and 256"));
    }
    Ok(())
}

fn validate_shell(input: &ShellInput) -> Result<(), FeatureError> {
    validate_snapshot("target", &input.target)?;
    exact_positive_nm("wall_thickness_nm", input.wall_thickness_nm)?;
    exact_positive_nm("tolerance_nm", input.tolerance_nm)?;
    if input.removed_face_stable_ids.len() != 1 {
        return Err(invalid(
            "removed_face_stable_ids",
            "the qualified prismatic Shell requires exactly one face to remove",
        ));
    }
    if input.removed_face_stable_ids.contains(&0) {
        return Err(invalid(
            "removed_face_stable_ids",
            "cannot contain the unassigned stable ID 0",
        ));
    }
    Ok(())
}

fn validate_mirror(input: &MirrorInput) -> Result<(), FeatureError> {
    validate_transform_source(&input.source)?;
    validate_exact_vector("plane_origin_nm", input.plane_origin_nm)?;
    exact_positive_nm("tolerance_nm", input.tolerance_nm)
}

fn validate_transform(input: &TransformInput) -> Result<(), FeatureError> {
    validate_transform_source(&input.source)?;
    validate_exact_vector("translation_nm", input.translation_nm)?;
    if input.translation_nm == [0, 0, 0] {
        return Err(invalid(
            "translation_nm",
            "must move the body by a non-zero exact displacement",
        ));
    }
    exact_positive_nm("tolerance_nm", input.tolerance_nm)
}

fn validate_linear_pattern(input: &LinearPatternInput) -> Result<(), FeatureError> {
    validate_transform_source(&input.source)?;
    validate_instance_ids(&input.instance_body_ids)?;
    validate_exact_vector("step_nm", input.step_nm)?;
    if input.step_nm == [0, 0, 0] {
        return Err(invalid("step_nm", "must translate each instance"));
    }
    exact_positive_nm("tolerance_nm", input.tolerance_nm)
}

fn validate_circular_pattern(input: &CircularPatternInput) -> Result<(), FeatureError> {
    validate_transform_source(&input.source)?;
    validate_instance_ids(&input.instance_body_ids)?;
    validate_exact_vector("axis_origin_nm", input.axis_origin_nm)?;
    if input.step_microdegrees == 0
        || input.step_microdegrees.unsigned_abs() > MICRODEGREES_PER_REVOLUTION as u64
    {
        return Err(invalid(
            "step_microdegrees",
            "must be non-zero and no greater than one revolution",
        ));
    }
    exact_positive_nm("tolerance_nm", input.tolerance_nm)
}

fn validate_transform_source(source: &TransformSource) -> Result<(), FeatureError> {
    match source {
        TransformSource::Body { body } => validate_snapshot("source.body", body),
        TransformSource::FeatureSequence {
            ordered_feature_ids,
            resolved_body,
        } => {
            validate_snapshot("source.resolved_body", resolved_body)?;
            if ordered_feature_ids.is_empty()
                || ordered_feature_ids.iter().any(|id| id.trim().is_empty())
            {
                return Err(invalid(
                    "source.ordered_feature_ids",
                    "must contain non-empty feature identities in evaluation order",
                ));
            }
            Ok(())
        }
    }
}

fn validate_instance_ids(ids: &[String]) -> Result<(), FeatureError> {
    if !(2..=1024).contains(&ids.len()) {
        return Err(invalid(
            "instance_body_ids",
            "must contain 2..=1024 ordered instance identities",
        ));
    }
    let mut unique = std::collections::BTreeSet::new();
    for id in ids {
        if id.trim().is_empty() || !unique.insert(id) {
            return Err(invalid(
                "instance_body_ids",
                "must contain unique non-empty caller identities",
            ));
        }
    }
    Ok(())
}

fn validate_exact_vector(field: &str, values: [i64; 3]) -> Result<(), FeatureError> {
    for (index, value) in values.into_iter().enumerate() {
        exact_nm(&format!("{field}[{index}]"), value)?;
    }
    Ok(())
}

fn validate_snapshot(field: &str, snapshot: &BodySnapshot) -> Result<(), FeatureError> {
    if snapshot.body_id.trim().is_empty() {
        return Err(invalid(
            field,
            "body_id must be a non-empty caller identity",
        ));
    }
    if snapshot.solid_json.is_empty() {
        return Err(invalid(
            field,
            "solid_json must contain a serialized kernel solid",
        ));
    }
    Ok(())
}

fn execute_revolve(input: &RevolveInput) -> Result<Solid, FeatureError> {
    let origin = point_from_nm(input.axis_origin_nm);
    let axis = match input.axis {
        PrincipalAxis::X => Vector3::unit_x(),
        PrincipalAxis::Y => Vector3::unit_y(),
        PrincipalAxis::Z => Vector3::unit_z(),
    };
    let inner = model_units(input.inner_radius_nm);
    let outer = model_units(input.outer_radius_nm);
    let start = model_units(input.axial_start_nm);
    let end = model_units(input.axial_end_nm);
    let points = match input.axis {
        PrincipalAxis::X => [
            origin + Vector3::new(start, inner, 0.0),
            origin + Vector3::new(end, inner, 0.0),
            origin + Vector3::new(end, outer, 0.0),
            origin + Vector3::new(start, outer, 0.0),
        ],
        PrincipalAxis::Y => [
            origin + Vector3::new(inner, start, 0.0),
            origin + Vector3::new(inner, end, 0.0),
            origin + Vector3::new(outer, end, 0.0),
            origin + Vector3::new(outer, start, 0.0),
        ],
        PrincipalAxis::Z => [
            origin + Vector3::new(inner, 0.0, start),
            origin + Vector3::new(outer, 0.0, start),
            origin + Vector3::new(outer, 0.0, end),
            origin + Vector3::new(inner, 0.0, end),
        ],
    };
    let face: Face =
        profile::attach_plane_normalized(vec![closed_wire(points)]).map_err(|error| {
            failure(
                ErrorCategory::InvalidInput,
                format!("revolve profile is invalid: {error}"),
                Some("profile"),
                "repair the radial profile dimensions",
            )
        })?;
    let sweep = if input.sweep_microdegrees == MICRODEGREES_PER_REVOLUTION {
        builder::SweepAngle::Closed
    } else {
        builder::SweepAngle::Partial(monstertruck_modeling::Rad(
            input.sweep_microdegrees as f64 / MICRODEGREES_PER_REVOLUTION as f64 * TAU,
        ))
    };
    Ok(builder::revolve(
        &face,
        origin,
        axis,
        sweep,
        input.divisions as usize,
    ))
}

#[cfg(not(target_arch = "wasm32"))]
fn execute_boolean(input: &BooleanInput) -> Result<Solid, FeatureError> {
    let mut result = decode_solid("target", &input.target)?;
    let tolerance = model_units(input.tolerance_nm);
    for (index, tool) in input.tools.iter().enumerate() {
        let tool_solid = decode_solid(&format!("tools[{index}]"), tool)?;
        let outcome = match input.operation {
            BooleanKind::Union => monstertruck_solid::or(&result, &tool_solid, tolerance),
            BooleanKind::Cut => monstertruck_solid::difference(&result, &tool_solid, tolerance),
            BooleanKind::Intersect => monstertruck_solid::and(&result, &tool_solid, tolerance),
        };
        result = match outcome {
            Ok(result) => result,
            Err(error) => {
                // Preserve the pinned native topology when it is valid. For
                // qualified rectangular prisms, retry the complete ordered
                // operation in the bounded exact cell domain; this recovers
                // true through-cuts that the adaptive backend can return as an
                // unoriented shell without perturbing successful downstream
                // edge-treatment workflows.
                if let Some(exact) = execute_qualified_orthogonal_boolean(input)? {
                    return Ok(exact);
                }
                return Err(map_boolean_error(error, index));
            }
        };
    }
    Ok(result)
}

/// Prefer the same bounded exact orthogonal-cell Boolean on native and WASM for
/// qualified axis-aligned prisms. This avoids routing a known exact class
/// through the pinned adaptive intersection backend, whose through-cut result
/// can be non-oriented even when the operands are valid closed boxes.
#[cfg(not(target_arch = "wasm32"))]
fn execute_qualified_orthogonal_boolean(
    input: &BooleanInput,
) -> Result<Option<Solid>, FeatureError> {
    let target = decode_solid("target", &input.target)?;
    let Some(mut cells) = qualified_axis_aligned_boxes(&target)? else {
        return Ok(None);
    };
    let mut tools = Vec::with_capacity(input.tools.len());
    for (index, snapshot) in input.tools.iter().enumerate() {
        let solid = decode_solid(&format!("tools[{index}]"), snapshot)?;
        let Some(boxes) = qualified_axis_aligned_boxes(&solid)? else {
            return Ok(None);
        };
        tools.push(boxes);
    }
    for (index, tool) in tools.iter().enumerate() {
        cells = orthogonal_boolean_cells(&cells, tool, input.operation).map_err(|message| {
            wasm_boolean_failure(
                input,
                index,
                ErrorCategory::Unsupported,
                message,
                "simplify the axis-aligned box operands and retry",
            )
        })?;
        if cells.is_empty() {
            return Err(wasm_boolean_failure(
                input,
                index,
                ErrorCategory::EmptyResult,
                "qualified axis-aligned box Boolean produced an empty result",
                "choose operands that leave non-zero volume",
            ));
        }
    }
    solid_from_orthogonal_cells(&cells)
        .map(Some)
        .map_err(|message| {
            wasm_boolean_failure(
                input,
                input.tools.len().saturating_sub(1),
                ErrorCategory::Unsupported,
                message,
                "simplify the axis-aligned box operands and retry",
            )
        })
}

/// Monstertruck's intersection backend reaches its generic adaptive curve
/// divider, which reads `std::time::Instant` and traps on `wasm32-unknown-unknown`.
/// Keep native execution unchanged. In the browser, execute a bounded exact
/// orthogonal-cell Boolean for axis-aligned rectangular prisms and retain the
/// previous proof-only cases for all other topology.
#[cfg(target_arch = "wasm32")]
fn execute_boolean(input: &BooleanInput) -> Result<Solid, FeatureError> {
    let mut result = decode_solid("target", &input.target)?;
    let mut result_json = input.target.solid_json.clone();
    let mut qualified_cells = qualified_axis_aligned_boxes(&result)?;
    let mut qualified_changed = false;
    for (index, tool_snapshot) in input.tools.iter().enumerate() {
        let tool = decode_solid(&format!("tools[{index}]"), tool_snapshot)?;
        let identical = result_json == tool_snapshot.solid_json;
        if identical && !qualified_changed {
            match input.operation {
                BooleanKind::Union | BooleanKind::Intersect => continue,
                BooleanKind::Cut => {
                    return Err(wasm_boolean_failure(
                        input,
                        index,
                        ErrorCategory::EmptyResult,
                        "cutting a body by the identical body produces an empty result",
                        "choose a tool that leaves non-zero volume",
                    ));
                }
            }
        }

        let tool_cells = qualified_axis_aligned_boxes(&tool)?;
        if let (Some(current), Some(tool_cells)) = (&qualified_cells, tool_cells.as_ref()) {
            let cells = orthogonal_boolean_cells(current, tool_cells, input.operation).map_err(
                |message| {
                    wasm_boolean_failure(
                        input,
                        index,
                        ErrorCategory::Unsupported,
                        message,
                        "simplify the axis-aligned box operands and retry",
                    )
                },
            )?;
            if cells.is_empty() {
                return Err(wasm_boolean_failure(
                    input,
                    index,
                    ErrorCategory::EmptyResult,
                    "qualified axis-aligned box Boolean produced an empty result",
                    "choose operands that leave non-zero volume",
                ));
            }
            qualified_cells = Some(cells);
            qualified_changed = true;
            // Defer B-rep construction until every ordered tool has been
            // evaluated. This keeps sequential operations in the exact cell
            // domain instead of attempting to re-qualify a concave result.
            continue;
        }

        // A qualified chain cannot be mixed with unsupported topology: doing
        // so would silently substitute bounding geometry. Refuse it verbatim.
        if qualified_changed {
            return Err(wasm_boolean_failure(
                input,
                index,
                ErrorCategory::Unsupported,
                "browser Boolean operands must all be exact axis-aligned rectangular prisms",
                "retain the operands and choose only qualified rectangular-prism bodies",
            ));
        }

        let disjoint = solids_are_disjoint(&result, &tool)?;
        match (input.operation, disjoint) {
            (BooleanKind::Union, true) => {
                let mut boundaries = result.into_boundaries();
                boundaries.extend(tool.into_boundaries());
                result = Solid::try_new(boundaries).map_err(|error| {
                    wasm_boolean_failure(
                        input,
                        index,
                        ErrorCategory::Unsupported,
                        format!("disjoint union produced an invalid solid: {error}"),
                        "simplify the operands and retry",
                    )
                })?;
                result_json = serde_json::to_vec(&result).map_err(|error| {
                    failure(
                        ErrorCategory::Unsupported,
                        format!("cannot compare the current boolean result: {error}"),
                        Some("target"),
                        "reload or rebuild the referenced body",
                    )
                })?;
                qualified_cells = None;
            }
            (BooleanKind::Cut, true) => {}
            (BooleanKind::Intersect, true) => {
                return Err(wasm_boolean_failure(
                    input,
                    index,
                    ErrorCategory::EmptyResult,
                    "intersection of disjoint bodies is empty",
                    "choose overlapping operands",
                ));
            }
            (_, false) => {
                return Err(wasm_boolean_failure(
                    input,
                    index,
                    ErrorCategory::Unsupported,
                    "overlapping non-identical booleans require the native intersection backend",
                    "retain the operands and run the operation in the native kernel",
                ));
            }
        }
    }
    if let Some(cells) = qualified_cells {
        solid_from_orthogonal_cells(&cells).map_err(|message| {
            wasm_boolean_failure(
                input,
                input.tools.len() - 1,
                ErrorCategory::Unsupported,
                message,
                "simplify the axis-aligned box operands and retry",
            )
        })
    } else {
        Ok(result)
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
struct QualifiedBoxNm {
    min: [i64; 3],
    max: [i64; 3],
}

/// Recognize only exact six-face rectangular-prism shells. Unique nanometer
/// coordinates make imported STEP boxes with face-local duplicate vertices
/// qualify without accepting a merely box-shaped bounding volume.
fn qualified_axis_aligned_boxes(
    solid: &Solid,
) -> Result<Option<Vec<QualifiedBoxNm>>, FeatureError> {
    let mut boxes = Vec::new();
    for shell in solid.boundaries() {
        if shell.face_iter().count() != 6 {
            return Ok(None);
        }
        let points = shell
            .vertex_iter()
            .map(|vertex| point_nm(vertex.point()))
            .collect::<Result<BTreeSet<_>, _>>()?;
        if points.len() != 8 {
            return Ok(None);
        }
        let min =
            std::array::from_fn(|axis| points.iter().map(|point| point[axis]).min().unwrap_or(0));
        let max =
            std::array::from_fn(|axis| points.iter().map(|point| point[axis]).max().unwrap_or(0));
        if (0..3).any(|axis| min[axis] >= max[axis]) {
            return Ok(None);
        }
        let expected = (0..8)
            .map(|corner| {
                std::array::from_fn(|axis| {
                    if corner & (1 << axis) == 0 {
                        min[axis]
                    } else {
                        max[axis]
                    }
                })
            })
            .collect::<BTreeSet<_>>();
        if points != expected {
            return Ok(None);
        }

        let mut planes = BTreeSet::new();
        for face in shell.face_iter() {
            let face_points = face
                .vertex_iter()
                .map(|vertex| point_nm(vertex.point()))
                .collect::<Result<BTreeSet<_>, _>>()?;
            if face_points.len() != 4 {
                return Ok(None);
            }
            let constant_axes = (0..3)
                .filter_map(|axis| {
                    let coordinate = face_points.first().expect("four face points")[axis];
                    face_points
                        .iter()
                        .all(|point| point[axis] == coordinate)
                        .then_some((axis, coordinate))
                })
                .collect::<Vec<_>>();
            if constant_axes.len() != 1 {
                return Ok(None);
            }
            let (axis, coordinate) = constant_axes[0];
            let positive = if coordinate == max[axis] {
                true
            } else if coordinate == min[axis] {
                false
            } else {
                return Ok(None);
            };
            for span_axis in (0..3).filter(|candidate| *candidate != axis) {
                let coordinates = face_points
                    .iter()
                    .map(|point| point[span_axis])
                    .collect::<BTreeSet<_>>();
                if coordinates != BTreeSet::from([min[span_axis], max[span_axis]]) {
                    return Ok(None);
                }
            }
            if !planes.insert((axis, positive)) {
                return Ok(None);
            }
        }
        if planes.len() != 6 {
            return Ok(None);
        }
        boxes.push(QualifiedBoxNm { min, max });
    }
    if boxes.is_empty() {
        return Ok(None);
    }
    boxes.sort_unstable();
    for (index, left) in boxes.iter().enumerate() {
        if boxes[index + 1..].iter().any(|right| {
            (0..3).all(|axis| left.min[axis] < right.max[axis] && right.min[axis] < left.max[axis])
        }) {
            return Ok(None);
        }
    }
    Ok(Some(boxes))
}

fn orthogonal_boolean_cells(
    current: &[QualifiedBoxNm],
    tools: &[QualifiedBoxNm],
    operation: BooleanKind,
) -> Result<Vec<QualifiedBoxNm>, &'static str> {
    let mut coordinates: [BTreeSet<i64>; 3] = std::array::from_fn(|_| BTreeSet::new());
    for cell in current.iter().chain(tools) {
        for (axis, values) in coordinates.iter_mut().enumerate() {
            values.insert(cell.min[axis]);
            values.insert(cell.max[axis]);
        }
    }
    let coordinates = coordinates.map(|axis| axis.into_iter().collect::<Vec<_>>());
    let candidate_count = coordinates
        .iter()
        .map(|axis| axis.len().saturating_sub(1))
        .product::<usize>();
    if candidate_count > MAX_QUALIFIED_BOOLEAN_CELLS {
        return Err("qualified browser Boolean exceeds the 4096-cell complexity bound");
    }
    let contains_midpoint = |boxes: &[QualifiedBoxNm], min: [i64; 3], max: [i64; 3]| {
        boxes.iter().any(|cell| {
            (0..3).all(|axis| {
                let midpoint_twice = min[axis] + max[axis];
                cell.min[axis] * 2 < midpoint_twice && midpoint_twice < cell.max[axis] * 2
            })
        })
    };
    let mut result = Vec::new();
    for x in 0..coordinates[0].len().saturating_sub(1) {
        for y in 0..coordinates[1].len().saturating_sub(1) {
            for z in 0..coordinates[2].len().saturating_sub(1) {
                let min = [coordinates[0][x], coordinates[1][y], coordinates[2][z]];
                let max = [
                    coordinates[0][x + 1],
                    coordinates[1][y + 1],
                    coordinates[2][z + 1],
                ];
                let in_current = contains_midpoint(current, min, max);
                let in_tools = contains_midpoint(tools, min, max);
                let include = match operation {
                    BooleanKind::Union => in_current || in_tools,
                    BooleanKind::Cut => in_current && !in_tools,
                    BooleanKind::Intersect => in_current && in_tools,
                };
                if include {
                    result.push(QualifiedBoxNm { min, max });
                }
            }
        }
    }
    coalesce_orthogonal_cells(&mut result);
    Ok(result)
}

fn coalesce_orthogonal_cells(cells: &mut Vec<QualifiedBoxNm>) {
    loop {
        cells.sort_unstable();
        let mut merged = None;
        'pairs: for left_index in 0..cells.len() {
            for right_index in left_index + 1..cells.len() {
                for axis in 0..3 {
                    let equal_other_spans =
                        (0..3)
                            .filter(|candidate| *candidate != axis)
                            .all(|candidate| {
                                cells[left_index].min[candidate]
                                    == cells[right_index].min[candidate]
                                    && cells[left_index].max[candidate]
                                        == cells[right_index].max[candidate]
                            });
                    if equal_other_spans
                        && (cells[left_index].max[axis] == cells[right_index].min[axis]
                            || cells[right_index].max[axis] == cells[left_index].min[axis])
                    {
                        let mut combined = cells[left_index];
                        combined.min[axis] = combined.min[axis].min(cells[right_index].min[axis]);
                        combined.max[axis] = combined.max[axis].max(cells[right_index].max[axis]);
                        merged = Some((left_index, right_index, combined));
                        break 'pairs;
                    }
                }
            }
        }
        let Some((left, right, combined)) = merged else {
            break;
        };
        cells.remove(right);
        cells.remove(left);
        cells.push(combined);
    }
}

fn solid_from_orthogonal_cells(cells: &[QualifiedBoxNm]) -> Result<Solid, String> {
    type GridIndex = (usize, usize, usize);
    type EdgeKey = ([i64; 3], [i64; 3]);

    let mut coordinates: [BTreeSet<i64>; 3] = std::array::from_fn(|_| BTreeSet::new());
    for cell in cells {
        for (axis, values) in coordinates.iter_mut().enumerate() {
            values.insert(cell.min[axis]);
            values.insert(cell.max[axis]);
        }
    }
    let coordinates = coordinates.map(|axis| axis.into_iter().collect::<Vec<_>>());
    let mut occupied = BTreeSet::<GridIndex>::new();
    for x in 0..coordinates[0].len().saturating_sub(1) {
        for y in 0..coordinates[1].len().saturating_sub(1) {
            for z in 0..coordinates[2].len().saturating_sub(1) {
                let min = [coordinates[0][x], coordinates[1][y], coordinates[2][z]];
                let max = [
                    coordinates[0][x + 1],
                    coordinates[1][y + 1],
                    coordinates[2][z + 1],
                ];
                if cells.iter().any(|cell| {
                    (0..3).all(|axis| cell.min[axis] <= min[axis] && max[axis] <= cell.max[axis])
                }) {
                    occupied.insert((x, y, z));
                }
            }
        }
    }

    let loops = [
        [0, 1, 3, 2], // -X
        [4, 6, 7, 5], // +X
        [0, 4, 5, 1], // -Y
        [2, 3, 7, 6], // +Y
        [0, 2, 6, 4], // -Z
        [1, 5, 7, 3], // +Z
    ];
    let neighbors = [
        (-1, 0, 0),
        (1, 0, 0),
        (0, -1, 0),
        (0, 1, 0),
        (0, 0, -1),
        (0, 0, 1),
    ];
    let mut vertices = BTreeMap::<[i64; 3], Vertex>::new();
    let mut edges = BTreeMap::<EdgeKey, Edge>::new();
    let mut faces = Vec::<(Face, Vec<EdgeKey>)>::new();
    for &(x, y, z) in &occupied {
        let corners = (0..8)
            .map(|corner| {
                [
                    coordinates[0][x + usize::from(corner & 4 != 0)],
                    coordinates[1][y + usize::from(corner & 2 != 0)],
                    coordinates[2][z + usize::from(corner & 1 != 0)],
                ]
            })
            .collect::<Vec<_>>();
        for (side, &(dx, dy, dz)) in neighbors.iter().enumerate() {
            let neighbor = (x as isize + dx, y as isize + dy, z as isize + dz);
            if neighbor.0 >= 0
                && neighbor.1 >= 0
                && neighbor.2 >= 0
                && occupied.contains(&(
                    neighbor.0 as usize,
                    neighbor.1 as usize,
                    neighbor.2 as usize,
                ))
            {
                continue;
            }
            let loop_points = loops[side].map(|corner| corners[corner]);
            let mut oriented = Vec::with_capacity(4);
            let mut face_keys = Vec::with_capacity(4);
            for edge_index in 0..4 {
                let front = loop_points[edge_index];
                let back = loop_points[(edge_index + 1) % 4];
                let key = if front < back {
                    (front, back)
                } else {
                    (back, front)
                };
                let edge = edges.entry(key).or_insert_with(|| {
                    let front_vertex = vertices
                        .entry(key.0)
                        .or_insert_with(|| builder::vertex(point_from_nm(key.0)))
                        .clone();
                    let back_vertex = vertices
                        .entry(key.1)
                        .or_insert_with(|| builder::vertex(point_from_nm(key.1)))
                        .clone();
                    builder::line(&front_vertex, &back_vertex)
                });
                oriented.push(if front < back {
                    edge.clone()
                } else {
                    edge.inverse()
                });
                face_keys.push(key);
            }
            let face = builder::try_attach_plane(vec![Wire::from(oriented)])
                .map_err(|error| format!("cannot construct qualified box face: {error}"))?;
            faces.push((face, face_keys));
        }
    }
    if faces.is_empty() {
        return Err("qualified box Boolean produced no boundary faces".to_owned());
    }

    let mut parents = (0..faces.len()).collect::<Vec<_>>();
    fn root(parents: &mut [usize], mut index: usize) -> usize {
        while parents[index] != index {
            parents[index] = parents[parents[index]];
            index = parents[index];
        }
        index
    }
    let mut edge_owner = BTreeMap::<EdgeKey, usize>::new();
    let mut edge_incidence = BTreeMap::<EdgeKey, usize>::new();
    for (face_index, (_, keys)) in faces.iter().enumerate() {
        for key in keys {
            *edge_incidence.entry(*key).or_default() += 1;
            if let Some(&other) = edge_owner.get(key) {
                let left = root(&mut parents, face_index);
                let right = root(&mut parents, other);
                parents[left] = right;
            } else {
                edge_owner.insert(*key, face_index);
            }
        }
    }
    if edge_incidence.values().any(|count| *count != 2) {
        return Err("qualified box Boolean would create a non-manifold boundary".to_owned());
    }
    let mut components = BTreeMap::<usize, Vec<Face>>::new();
    for (index, (face, _)) in faces.into_iter().enumerate() {
        let component = root(&mut parents, index);
        components.entry(component).or_default().push(face);
    }
    let shells = components
        .into_values()
        .map(|faces| faces.into_iter().collect::<Shell>())
        .collect::<Vec<_>>();
    Solid::try_new(shells)
        .map_err(|error| format!("qualified box Boolean produced an invalid solid: {error}"))
}

#[cfg(target_arch = "wasm32")]
fn solids_are_disjoint(left: &Solid, right: &Solid) -> Result<bool, FeatureError> {
    let left_points = left
        .vertex_iter()
        .map(|vertex| vertex.point())
        .collect::<Vec<_>>();
    let right_points = right
        .vertex_iter()
        .map(|vertex| vertex.point())
        .collect::<Vec<_>>();
    let left = bounds_nm(&left_points)?;
    let right = bounds_nm(&right_points)?;
    Ok((0..3).any(|axis| left.max[axis] < right.min[axis] || right.max[axis] < left.min[axis]))
}

fn wasm_boolean_failure(
    input: &BooleanInput,
    tool_index: usize,
    category: ErrorCategory,
    message: impl Into<String>,
    recovery: impl Into<String>,
) -> FeatureError {
    FeatureError {
        category,
        message: message.into(),
        field: Some(format!("tools[{tool_index}]")),
        recovery: recovery.into(),
        preserved_inputs: std::iter::once(input.target.clone())
            .chain(input.tools.iter().cloned())
            .collect(),
        problematic_reference: Some(Box::new(ProblematicReference {
            kind: ReferenceKind::Body,
            stable_id: input.tools[tool_index].body_id.clone(),
            ordered_index: Some(tool_index),
        })),
    }
}

fn execute_edge_treatment(
    input: &EdgeTreatmentInput,
    profile: FilletProfile,
) -> Result<Solid, FeatureError> {
    let solid = decode_solid("target", &input.target)?;
    let mut boundaries = solid.into_boundaries();
    let mut found = std::collections::BTreeSet::new();
    for shell in &mut boundaries {
        let selected: Vec<_> = input
            .edge_stable_ids
            .iter()
            .filter_map(|stable_id| {
                shell
                    .edge_iter()
                    .find(|edge| edge.stable_id().raw() == *stable_id)
                    .inspect(|_| {
                        found.insert(*stable_id);
                    })
            })
            .collect();
        if selected.is_empty() {
            continue;
        }
        let options = FilletOptions {
            radius: RadiusSpec::Constant(model_units(input.radius_nm)),
            divisions: NonZeroUsize::new(input.divisions as usize).expect("validated non-zero"),
            profile: profile.clone(),
        };
        fillet_edges(shell, &selected, Some(&options)).map_err(|error| {
            unsupported_preserving(
                format!("pinned edge treatment rejected the selected topology: {error}"),
                "edge_stable_ids",
                &input.target,
                selected.first().map(|edge| ProblematicReference {
                    kind: ReferenceKind::Edge,
                    stable_id: edge.stable_id().raw().to_string(),
                    ordered_index: input
                        .edge_stable_ids
                        .iter()
                        .position(|id| *id == edge.stable_id().raw()),
                }),
            )
        })?;
    }
    if let Some((index, missing)) = input
        .edge_stable_ids
        .iter()
        .enumerate()
        .find(|(_, id)| !found.contains(id))
    {
        let mut error = invalid(
            "edge_stable_ids",
            "contains a reference absent from the target",
        );
        error.preserved_inputs.push(input.target.clone());
        error.problematic_reference = Some(Box::new(ProblematicReference {
            kind: ReferenceKind::Edge,
            stable_id: missing.to_string(),
            ordered_index: Some(index),
        }));
        return Err(error);
    }
    Solid::try_new(boundaries).map_err(|error| {
        unsupported_preserving(
            format!("pinned edge treatment produced an invalid solid: {error}"),
            "target",
            &input.target,
            None,
        )
    })
}

#[derive(Debug, Clone, Copy)]
struct ShellFrame {
    bounds: AxisAlignedBoundsNm,
    removed_axis: usize,
    removed_positive: bool,
}

#[derive(Debug, Clone, Copy)]
struct DirectedAxis {
    axis: usize,
    positive: bool,
}

/// Build an exact closed-manifold cup from one axis-aligned rectangular prism.
/// This is a real boundary representation with shared edges: five outer faces,
/// five cavity faces, and four opening-rim faces. Unsupported topology never
/// falls back to a mesh or bounding-box approximation.
fn execute_shell(input: &ShellInput) -> Result<Solid, FeatureError> {
    let source = decode_solid("target", &input.target)?;
    let frame = qualified_shell_frame(input, &source)?;
    let [u_axis, v_axis, w_axis] = shell_basis(frame);
    let span = |axis: DirectedAxis| frame.bounds.max[axis.axis] - frame.bounds.min[axis.axis];
    let [du, dv, dw] = [span(u_axis), span(v_axis), span(w_axis)];
    let thickness = input.wall_thickness_nm;
    if thickness
        .checked_mul(2)
        .is_none_or(|twice| twice >= du || twice >= dv)
        || thickness >= dw
    {
        return Err(shell_input_error(
            input,
            ErrorCategory::InvalidInput,
            "wall_thickness_nm",
            "wall thickness leaves no positive interior cavity",
            "reduce Wall thickness below half of both face dimensions and below the body depth",
        ));
    }

    let local = [
        [0, 0, 0],
        [du, 0, 0],
        [du, dv, 0],
        [0, dv, 0],
        [0, 0, dw],
        [du, 0, dw],
        [du, dv, dw],
        [0, dv, dw],
        [thickness, thickness, thickness],
        [du - thickness, thickness, thickness],
        [du - thickness, dv - thickness, thickness],
        [thickness, dv - thickness, thickness],
        [thickness, thickness, dw],
        [du - thickness, thickness, dw],
        [du - thickness, dv - thickness, dw],
        [thickness, dv - thickness, dw],
    ];
    let vertices: Vec<Vertex> = local
        .into_iter()
        .map(|point| {
            builder::vertex(shell_world_point(
                frame.bounds,
                [u_axis, v_axis, w_axis],
                point,
            ))
        })
        .collect();
    // Every loop is counter-clockwise from the material exterior. Reusing the
    // same edge object in opposite directions makes the result an oriented,
    // closed, non-singular shell instead of a collection of coincident faces.
    let loops = [
        [0, 3, 2, 1],
        [0, 1, 5, 4],
        [1, 2, 6, 5],
        [2, 3, 7, 6],
        [3, 0, 4, 7],
        [8, 9, 10, 11],
        [8, 12, 13, 9],
        [9, 13, 14, 10],
        [10, 14, 15, 11],
        [11, 15, 12, 8],
        [4, 5, 13, 12],
        [5, 6, 14, 13],
        [6, 7, 15, 14],
        [7, 4, 12, 15],
    ];
    let mut edges = BTreeMap::new();
    let faces = loops
        .into_iter()
        .map(|indices| shell_planar_face(&vertices, &mut edges, indices, input))
        .collect::<Result<Vec<_>, _>>()?;
    let shell: Shell = faces.into_iter().collect();
    Solid::try_new(vec![shell]).map_err(|error| {
        shell_input_error(
            input,
            ErrorCategory::Unsupported,
            "target",
            format!("qualified prismatic Shell produced an invalid boundary: {error}"),
            "repair the source body or choose another planar box face",
        )
    })
}

fn exact_shell_volume(input: &ShellInput) -> Result<f64, FeatureError> {
    let source = decode_solid("target", &input.target)?;
    let frame = qualified_shell_frame(input, &source)?;
    let [u_axis, v_axis, w_axis] = shell_basis(frame);
    let span =
        |axis: DirectedAxis| model_units(frame.bounds.max[axis.axis] - frame.bounds.min[axis.axis]);
    let [du, dv, dw] = [span(u_axis), span(v_axis), span(w_axis)];
    let thickness = model_units(input.wall_thickness_nm);
    Ok(du * dv * dw - (du - 2.0 * thickness) * (dv - 2.0 * thickness) * (dw - thickness))
}

fn qualified_shell_frame(input: &ShellInput, solid: &Solid) -> Result<ShellFrame, FeatureError> {
    if solid.boundaries().len() != 1 || solid.face_iter().count() != 6 {
        return Err(shell_input_error(
            input,
            ErrorCategory::Unsupported,
            "target",
            "Shell currently requires one six-face axis-aligned rectangular prism",
            "select an unmodified rectangular-prism body",
        ));
    }
    let points = solid
        .vertex_iter()
        .map(|vertex| point_nm(vertex.point()))
        .collect::<Result<BTreeSet<_>, _>>()?;
    let bounds = bounds_nm(
        &solid
            .vertex_iter()
            .map(|vertex| vertex.point())
            .collect::<Vec<_>>(),
    )?;
    let expected = (0..8)
        .map(|corner| {
            std::array::from_fn(|axis| {
                if corner & (1 << axis) == 0 {
                    bounds.min[axis]
                } else {
                    bounds.max[axis]
                }
            })
        })
        .collect::<BTreeSet<[i64; 3]>>();
    if points != expected || (0..3).any(|axis| bounds.min[axis] >= bounds.max[axis]) {
        return Err(shell_input_error(
            input,
            ErrorCategory::Unsupported,
            "target",
            "Shell source is not an exact axis-aligned rectangular prism",
            "select an unmodified rectangular-prism body",
        ));
    }

    let selected_id = input.removed_face_stable_ids[0];
    let selected = solid
        .face_iter()
        .find(|face| face.stable_id().raw() == selected_id)
        .ok_or_else(|| {
            shell_reference_error(
                input,
                ErrorCategory::InvalidInput,
                "removed_face_stable_ids",
                "selected face reference is absent from the target",
                "select one current outer face and retry",
            )
        })?;
    let face_points = selected
        .vertex_iter()
        .map(|vertex| point_nm(vertex.point()))
        .collect::<Result<BTreeSet<_>, _>>()?;
    if face_points.len() != 4 {
        return Err(shell_reference_error(
            input,
            ErrorCategory::Unsupported,
            "removed_face_stable_ids",
            "selected face is not a rectangular outer face",
            "select one planar rectangular-prism face",
        ));
    }
    let candidates = (0..3)
        .filter_map(|axis| {
            let coordinate = face_points.first().expect("validated face points")[axis];
            face_points
                .iter()
                .all(|point| point[axis] == coordinate)
                .then_some((axis, coordinate))
        })
        .collect::<Vec<_>>();
    if candidates.len() != 1 {
        return Err(shell_reference_error(
            input,
            ErrorCategory::Unsupported,
            "removed_face_stable_ids",
            "selected face has no unique principal normal",
            "select one axis-aligned rectangular-prism face",
        ));
    }
    let (removed_axis, coordinate) = candidates[0];
    let removed_positive = if coordinate == bounds.max[removed_axis] {
        true
    } else if coordinate == bounds.min[removed_axis] {
        false
    } else {
        return Err(shell_reference_error(
            input,
            ErrorCategory::Unsupported,
            "removed_face_stable_ids",
            "selected face is not on the source body's outer bound",
            "select one outer rectangular-prism face",
        ));
    };
    for axis in (0..3).filter(|axis| *axis != removed_axis) {
        let coordinates = face_points
            .iter()
            .map(|point| point[axis])
            .collect::<BTreeSet<_>>();
        if coordinates != BTreeSet::from([bounds.min[axis], bounds.max[axis]]) {
            return Err(shell_reference_error(
                input,
                ErrorCategory::Unsupported,
                "removed_face_stable_ids",
                "selected face does not span the source body's outer bounds",
                "select one outer rectangular-prism face",
            ));
        }
    }
    Ok(ShellFrame {
        bounds,
        removed_axis,
        removed_positive,
    })
}

fn shell_basis(frame: ShellFrame) -> [DirectedAxis; 3] {
    let positive = |axis| DirectedAxis {
        axis,
        positive: true,
    };
    let negative = |axis| DirectedAxis {
        axis,
        positive: false,
    };
    match (frame.removed_axis, frame.removed_positive) {
        (2, true) => [positive(0), positive(1), positive(2)],
        (2, false) => [positive(0), negative(1), negative(2)],
        (0, true) => [positive(1), positive(2), positive(0)],
        (0, false) => [positive(1), negative(2), negative(0)],
        (1, true) => [positive(2), positive(0), positive(1)],
        (1, false) => [positive(2), negative(0), negative(1)],
        _ => unreachable!("principal axis is bounded by validation"),
    }
}

fn shell_world_point(
    bounds: AxisAlignedBoundsNm,
    basis: [DirectedAxis; 3],
    local_nm: [i64; 3],
) -> Point3 {
    let mut world_nm = [0; 3];
    for (coordinate, axis) in local_nm.into_iter().zip(basis) {
        world_nm[axis.axis] = if axis.positive {
            bounds.min[axis.axis] + coordinate
        } else {
            bounds.max[axis.axis] - coordinate
        };
    }
    point_from_nm(world_nm)
}

fn shell_planar_face(
    vertices: &[Vertex],
    edges: &mut BTreeMap<(usize, usize), Edge>,
    indices: [usize; 4],
    input: &ShellInput,
) -> Result<Face, FeatureError> {
    let mut oriented = Vec::with_capacity(4);
    for index in 0..4 {
        let front = indices[index];
        let back = indices[(index + 1) % 4];
        let key = if front < back {
            (front, back)
        } else {
            (back, front)
        };
        let edge = edges
            .entry(key)
            .or_insert_with(|| builder::line(&vertices[key.0], &vertices[key.1]));
        oriented.push(if front < back {
            edge.clone()
        } else {
            edge.inverse()
        });
    }
    builder::try_attach_plane(vec![Wire::from(oriented)]).map_err(|error| {
        shell_input_error(
            input,
            ErrorCategory::Unsupported,
            "target",
            format!("cannot construct an exact planar Shell boundary: {error}"),
            "repair the source body or choose another planar box face",
        )
    })
}

fn shell_reference_error(
    input: &ShellInput,
    category: ErrorCategory,
    field: &str,
    message: impl Into<String>,
    recovery: impl Into<String>,
) -> FeatureError {
    let mut error = shell_input_error(input, category, field, message, recovery);
    error.problematic_reference = Some(Box::new(ProblematicReference {
        kind: ReferenceKind::Face,
        stable_id: input.removed_face_stable_ids[0].to_string(),
        ordered_index: Some(0),
    }));
    error
}

fn shell_input_error(
    input: &ShellInput,
    category: ErrorCategory,
    field: &str,
    message: impl Into<String>,
    recovery: impl Into<String>,
) -> FeatureError {
    let mut error = failure(category, message, Some(field), recovery);
    error.preserved_inputs.push(input.target.clone());
    error
}

fn point_nm(point: Point3) -> Result<[i64; 3], FeatureError> {
    Ok([
        model_coordinate_nm(point[0])?,
        model_coordinate_nm(point[1])?,
        model_coordinate_nm(point[2])?,
    ])
}

fn resolve_transform_source(source: &TransformSource) -> Result<&BodySnapshot, FeatureError> {
    match source {
        TransformSource::Body { body } => Ok(body),
        TransformSource::FeatureSequence {
            ordered_feature_ids,
            resolved_body,
        } => Err(unsupported_preserving(
            "feature-sequence transforms require feature-graph re-evaluation; the body kernel will not substitute a body transform",
            "source.ordered_feature_ids",
            resolved_body,
            ordered_feature_ids.first().map(|id| ProblematicReference {
                kind: ReferenceKind::Feature,
                stable_id: id.clone(),
                ordered_index: Some(0),
            }),
        )),
    }
}

fn execute_mirror(input: &MirrorInput, body: &BodySnapshot) -> Result<Solid, FeatureError> {
    let source = decode_solid("source.body", body)?;
    let scalars = match input.plane_normal {
        PrincipalAxis::X => Vector3::new(-1.0, 1.0, 1.0),
        PrincipalAxis::Y => Vector3::new(1.0, -1.0, 1.0),
        PrincipalAxis::Z => Vector3::new(1.0, 1.0, -1.0),
    };
    let mut mirrored = builder::scaled(&source, point_from_nm(input.plane_origin_nm), scalars);
    mirrored.not();
    Ok(mirrored)
}

fn execute_transform(input: &TransformInput, body: &BodySnapshot) -> Result<Solid, FeatureError> {
    let source = decode_solid("source.body", body)?;
    Ok(builder::translated(
        &source,
        Vector3::new(
            model_units(input.translation_nm[0]),
            model_units(input.translation_nm[1]),
            model_units(input.translation_nm[2]),
        ),
    ))
}

fn execute_linear_pattern(
    input: &LinearPatternInput,
    body: &BodySnapshot,
) -> Result<Solid, FeatureError> {
    let source = decode_solid("source.body", body)?;
    let step = Vector3::new(
        model_units(input.step_nm[0]),
        model_units(input.step_nm[1]),
        model_units(input.step_nm[2]),
    );
    let instances = (0..input.instance_body_ids.len())
        .map(|index| builder::translated(&source, step * index as f64));
    compound_instances(instances, body, "linear pattern")
}

fn execute_circular_pattern(
    input: &CircularPatternInput,
    body: &BodySnapshot,
) -> Result<Solid, FeatureError> {
    let source = decode_solid("source.body", body)?;
    let origin = point_from_nm(input.axis_origin_nm);
    let axis = match input.axis {
        PrincipalAxis::X => Vector3::unit_x(),
        PrincipalAxis::Y => Vector3::unit_y(),
        PrincipalAxis::Z => Vector3::unit_z(),
    };
    let step = input.step_microdegrees as f64 / MICRODEGREES_PER_REVOLUTION as f64 * TAU;
    let instances = (0..input.instance_body_ids.len()).map(|index| {
        builder::rotated(
            &source,
            origin,
            axis,
            monstertruck_modeling::Rad(step * index as f64),
        )
    });
    compound_instances(instances, body, "circular pattern")
}

fn compound_instances(
    instances: impl Iterator<Item = Solid>,
    source: &BodySnapshot,
    operation: &str,
) -> Result<Solid, FeatureError> {
    let boundaries = instances.flat_map(Solid::into_boundaries).collect();
    Solid::try_new(boundaries).map_err(|error| {
        unsupported_preserving(
            format!("pinned transform kernel rejected {operation}: {error}"),
            "source.body",
            source,
            None,
        )
    })
}

fn decode_solid(field: &str, snapshot: &BodySnapshot) -> Result<Solid, FeatureError> {
    serde_json::from_slice(&snapshot.solid_json).map_err(|error| {
        failure(
            ErrorCategory::InvalidInput,
            format!("{field} is not a serialized Monstertruck solid: {error}"),
            Some(field),
            "reload or rebuild the referenced body",
        )
    })
}

#[cfg(not(target_arch = "wasm32"))]
fn map_boolean_error(error: ShapeOpsError, tool_index: usize) -> FeatureError {
    let field = format!("tools[{tool_index}]");
    match error {
        ShapeOpsError::InvalidTolerance => invalid("tolerance_nm", "kernel rejected tolerance"),
        ShapeOpsError::NoBackend => failure(
            ErrorCategory::Unsupported,
            error.to_string(),
            Some("operation"),
            "enable the pinned marching-ssi backend before executing booleans",
        ),
        ShapeOpsError::EmptyOutputShell { .. } => failure(
            ErrorCategory::EmptyResult,
            error.to_string(),
            Some(&field),
            "edit the ordered tool so the boolean has non-empty volume",
        ),
        other => failure(
            ErrorCategory::Unsupported,
            format!("pinned boolean kernel rejected {field}: {other}"),
            Some(&field),
            "simplify the operands or adjust the explicit tolerance",
        ),
    }
}

fn geometry_evidence(
    solid: &Solid,
    tolerance_nm: i64,
    request: &FeatureRequest,
) -> Result<GeometryEvidence, FeatureError> {
    let points: Vec<Point3> = solid.vertex_iter().map(|vertex| vertex.point()).collect();
    let bounds = bounds_nm(&points)?;
    let tolerance = model_units(tolerance_nm);
    let volume = if let FeatureOperation::Shell(input) = &request.operation {
        exact_shell_volume(input)?
    } else {
        #[cfg(not(target_arch = "wasm32"))]
        {
            solid.triangulation(tolerance).to_polygon().volume().abs()
        }
        #[cfg(target_arch = "wasm32")]
        {
            let mut sampled = solid.clone();
            let packet = crawler_render_packet::packet_from_solid(&mut sampled, tolerance)
                .map_err(|error| {
                    failure(
                        ErrorCategory::Numerical,
                        format!("Crawler WASM sampler rejected kernel body: {error}"),
                        Some("tolerance_nm"),
                        "adjust tolerance or simplify the feature geometry",
                    )
                })?;
            sampled_packet_volume(&packet).max(bounds_volume(bounds))
        }
    };
    if !volume.is_finite() {
        return Err(failure(
            ErrorCategory::Numerical,
            "kernel produced a non-finite volume",
            Some("tolerance_nm"),
            "increase tolerance or reduce model dimensions",
        ));
    }
    if volume <= f64::EPSILON {
        return Err(failure(
            ErrorCategory::EmptyResult,
            "operation produced zero measurable volume",
            None,
            "edit the feature so the result has non-zero volume",
        ));
    }
    let vertex_count = solid.vertex_iter().count();
    let edge_count = solid.edge_iter().count();
    let face_count = solid.face_iter().count();
    let canonical = serde_json::to_vec(&(
        request,
        vertex_count,
        edge_count,
        face_count,
        bounds,
        volume.to_bits(),
    ))
    .map_err(|error| {
        failure(
            ErrorCategory::Unsupported,
            format!("cannot canonicalize feature evidence: {error}"),
            None,
            "simplify the feature DTO",
        )
    })?;
    Ok(GeometryEvidence {
        vertex_count,
        edge_count,
        face_count,
        bounds_nm: bounds,
        volume_model_units3: volume,
        deterministic_digest: format!("fnv1a64:{:016x}", fnv1a64(&canonical)),
    })
}

#[cfg(target_arch = "wasm32")]
fn sampled_packet_volume(packet: &crawler_render_packet::RenderPacket) -> f64 {
    packet
        .triangle_indices
        .chunks_exact(3)
        .map(|triangle| {
            let point = |index: u32| {
                let offset = index as usize * 3;
                [
                    packet.positions[offset] as f64,
                    packet.positions[offset + 1] as f64,
                    packet.positions[offset + 2] as f64,
                ]
            };
            let a = point(triangle[0]);
            let b = point(triangle[1]);
            let c = point(triangle[2]);
            (a[0] * (b[1] * c[2] - b[2] * c[1])
                + a[1] * (b[2] * c[0] - b[0] * c[2])
                + a[2] * (b[0] * c[1] - b[1] * c[0]))
                / 6.0
        })
        .sum::<f64>()
        .abs()
}

#[cfg(target_arch = "wasm32")]
fn bounds_volume(bounds: AxisAlignedBoundsNm) -> f64 {
    bounds
        .min
        .into_iter()
        .zip(bounds.max)
        .map(|(min, max)| (max - min).max(0) as f64 / NANOMETERS_PER_MODEL_UNIT)
        .product::<f64>()
        * f64::EPSILON
}

fn closed_wire(points: [Point3; 4]) -> Wire {
    let vertices = points.map(builder::vertex);
    vec![
        builder::line(&vertices[0], &vertices[1]),
        builder::line(&vertices[1], &vertices[2]),
        builder::line(&vertices[2], &vertices[3]),
        builder::line(&vertices[3], &vertices[0]),
    ]
    .into()
}

fn bounds_nm(points: &[Point3]) -> Result<AxisAlignedBoundsNm, FeatureError> {
    if points.is_empty() {
        return Err(failure(
            ErrorCategory::EmptyResult,
            "solid has no vertices",
            None,
            "edit the feature so it creates a bounded solid",
        ));
    }
    let mut min = [f64::INFINITY; 3];
    let mut max = [f64::NEG_INFINITY; 3];
    for point in points {
        for axis in 0..3 {
            min[axis] = min[axis].min(point[axis]);
            max[axis] = max[axis].max(point[axis]);
        }
    }
    Ok(AxisAlignedBoundsNm {
        min: [
            model_coordinate_nm(min[0])?,
            model_coordinate_nm(min[1])?,
            model_coordinate_nm(min[2])?,
        ],
        max: [
            model_coordinate_nm(max[0])?,
            model_coordinate_nm(max[1])?,
            model_coordinate_nm(max[2])?,
        ],
    })
}

fn model_coordinate_nm(value: f64) -> Result<i64, FeatureError> {
    let nm = value * NANOMETERS_PER_MODEL_UNIT;
    if !nm.is_finite() || nm.abs() > MAX_EXACT_NANOMETERS as f64 {
        return Err(failure(
            ErrorCategory::Numerical,
            "geometry bounds exceed exact nanometer range",
            None,
            "reduce model dimensions",
        ));
    }
    Ok(nm.round() as i64)
}

fn point_from_nm(value: [i64; 3]) -> Point3 {
    Point3::new(
        model_units(value[0]),
        model_units(value[1]),
        model_units(value[2]),
    )
}

fn model_units(value: i64) -> f64 {
    value as f64 / NANOMETERS_PER_MODEL_UNIT
}

fn exact_nm(field: &str, value: i64) -> Result<(), FeatureError> {
    if value.unsigned_abs() > MAX_EXACT_NANOMETERS as u64 {
        return Err(failure(
            ErrorCategory::Numerical,
            format!("{field} exceeds exact nanometer range"),
            Some(field),
            "reduce the absolute value to 9007199254740991 nanometers or less",
        ));
    }
    Ok(())
}

fn exact_positive_nm(field: &str, value: i64) -> Result<(), FeatureError> {
    exact_nm(field, value)?;
    if value <= 0 {
        return Err(invalid(field, "must be an integer greater than zero"));
    }
    Ok(())
}

fn invalid(field: &str, detail: &str) -> FeatureError {
    failure(
        ErrorCategory::InvalidInput,
        format!("{field} {detail}"),
        Some(field),
        "edit the typed feature input and retry",
    )
}

fn failure(
    category: ErrorCategory,
    message: impl Into<String>,
    field: Option<&str>,
    recovery: impl Into<String>,
) -> FeatureError {
    FeatureError {
        category,
        message: message.into(),
        field: field.map(str::to_owned),
        recovery: recovery.into(),
        preserved_inputs: Vec::new(),
        problematic_reference: None,
    }
}

fn unsupported_preserving(
    message: impl Into<String>,
    field: &str,
    input: &BodySnapshot,
    problematic_reference: Option<ProblematicReference>,
) -> FeatureError {
    FeatureError {
        category: ErrorCategory::Unsupported,
        message: message.into(),
        field: Some(field.to_owned()),
        recovery: "retain the original input and choose a qualified operation".to_owned(),
        preserved_inputs: vec![input.clone()],
        problematic_reference: problematic_reference.map(Box::new),
    }
}

fn fnv1a64(bytes: &[u8]) -> u64 {
    bytes.iter().fold(0xcbf29ce484222325, |hash, byte| {
        (hash ^ u64::from(*byte)).wrapping_mul(0x100000001b3)
    })
}

#[cfg(test)]
mod qualified_box_boolean_tests {
    use super::*;

    fn box_solid(min: [i64; 3], max: [i64; 3]) -> Solid {
        let vertex = builder::vertex(point_from_nm(min));
        let edge = builder::extrude(&vertex, Vector3::unit_x() * model_units(max[0] - min[0]));
        let face = builder::extrude(&edge, Vector3::unit_y() * model_units(max[1] - min[1]));
        builder::extrude(&face, Vector3::unit_z() * model_units(max[2] - min[2]))
    }

    fn qualified_box(min: [i64; 3], max: [i64; 3]) -> QualifiedBoxNm {
        QualifiedBoxNm { min, max }
    }

    #[test]
    fn overlapping_non_identical_boxes_have_exact_boolean_volumes() {
        let target = qualified_box([0, 0, 0], [2_000_000, 2_000_000, 2_000_000]);
        let tool = qualified_box(
            [1_000_000, 1_000_000, 1_000_000],
            [3_000_000, 3_000_000, 3_000_000],
        );
        for (operation, expected_volume) in [
            (BooleanKind::Union, 15.0),
            (BooleanKind::Cut, 7.0),
            (BooleanKind::Intersect, 1.0),
        ] {
            let cells = orthogonal_boolean_cells(&[target], &[tool], operation).unwrap();
            let solid = solid_from_orthogonal_cells(&cells).unwrap();
            let volume = solid.triangulation(0.01).to_polygon().volume().abs();
            assert!(
                (volume - expected_volume).abs() < 1.0e-9,
                "{operation:?}: actual={volume}, expected={expected_volume}"
            );
        }
    }

    #[test]
    fn qualified_box_output_is_deterministic_and_recognizes_import_style_duplicates() {
        let target = box_solid([0, 0, 0], [2_000_000, 2_000_000, 2_000_000]);
        let boxes = qualified_axis_aligned_boxes(&target).unwrap().unwrap();
        assert_eq!(
            boxes,
            [qualified_box([0, 0, 0], [2_000_000, 2_000_000, 2_000_000])]
        );
        let tool = qualified_box(
            [1_000_000, 1_000_000, 1_000_000],
            [3_000_000, 3_000_000, 3_000_000],
        );
        let first = orthogonal_boolean_cells(&boxes, &[tool], BooleanKind::Union).unwrap();
        let second = orthogonal_boolean_cells(&boxes, &[tool], BooleanKind::Union).unwrap();
        assert_eq!(first, second);
        assert_eq!(
            serde_json::to_vec(&solid_from_orthogonal_cells(&first).unwrap()).unwrap(),
            serde_json::to_vec(&solid_from_orthogonal_cells(&second).unwrap()).unwrap()
        );
    }

    #[test]
    fn non_prismatic_topology_does_not_qualify() {
        let input = RevolveInput {
            axis_origin_nm: [0, 0, 0],
            axis: PrincipalAxis::Z,
            inner_radius_nm: 0,
            outer_radius_nm: 1_000_000,
            axial_start_nm: 0,
            axial_end_nm: 2_000_000,
            sweep_microdegrees: MICRODEGREES_PER_REVOLUTION,
            divisions: 8,
            tolerance_nm: 10_000,
        };
        let revolved = execute_revolve(&input).unwrap();
        assert!(qualified_axis_aligned_boxes(&revolved).unwrap().is_none());
    }
}
